### ISSUE TITLE
make under Ubuntu 20.04 problem

### ISSUE THREAD

**Issue by andynameistaken** [craflin/umdoc#14]
Could you update  README.md  with dependencies for building this project: `xelatex`, `texlive`, additional fonts like Source Sans Pro, etc?

Anyway, project hangs on `make` (installed `texlive`, `texlive-fonts-extra`, `texlive-xetex`, `g++` and `cmake`):
```
xelatex: unrecognized option '--aux-directory=/home/andy/git/umdoc/Doc/umdoc'
xelatex: unrecognized option '--aux-directory=/home/andy/git/umdoc/Doc/umdoc'
error: Could not copy file 'circle.png' to '/home/andy/git/umdoc/Doc/circle.png': Success
xelatex: unrecognized option '--aux-directory=/home/andy/git/umdoc/Examples/coverpage'
xelatex: unrecognized option '--aux-directory=/home/andy/git/umdoc/Examples/coverpage'
xelatex: unrecognized option '--aux-directory=/home/andy/git/umdoc/Examples/customenvironment'
xelatex: unrecognized option '--aux-directory=/home/andy/git/umdoc/Examples/customenvironment'
xelatex: unrecognized option '--aux-directory=/home/andy/git/umdoc/Examples/md2pdf'
xelatex: unrecognized option '--aux-directory=/home/andy/git/umdoc/Examples/md2pdf'
xelatex: unrecognized option '--aux-directory=/home/andy/git/umdoc/Examples/codeblocks'
xelatex: unrecognized option '--aux-directory=/home/andy/git/umdoc/Examples/codeblocks'
```
It is indefinitely on 91% with generating environmentscrpt.pdf

**Comment by craflin** [comment]
Hi, I've updated the readme, but I don't know why it hangs on your system. So I think the problem is unrelated to the dependencies.
Anyways there was an issue with environment scripts that has been fixed with 0.2.9, so it might work now. Please try again and create a new ticket if there is still an issue. A stack track would be helpful if it still hangs, you can create it with `gdb -p <pid>`, then wait a little press `CTRL+C` and then execute `bt`.
